language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mistydev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mistydev/react-test npm run test

after_success:
  - docker build -t mistydev/multi-client ./client
  - docker build -t mistydev/multi-nginx ./nginx
  - docker build -t mistydev/multi-server ./server
  - docker build -t mistydev/multi-worker ./worker
  # Log in to the docker CLI
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  # Take those images and push them to docker hub
  - docker push mistydev/multi-client
  - docker push mistydev/multi-nginx
  - docker push mistydev/multi-server
  - docker push mistydev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-811607584264
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: ${AWS_ACCESS_KEY}
  secret_access_key:
    secure: ${AWS_SECRET_KEY}
